[tool.black]

line-length = 120
py36 = true
include = '\.pyi?$'
# see help text for default exclude
exclude = '''/(
    # black defaults from --help (see also https://github.com/ambv/black#configuration-format )
      \.git
    | \.hg
    | \.mypy_cache
    | \.nox
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist

    # django specific exclusions

    | migrations

    # project specific exclusions
)/
'''
